### ISSUE TITLE
Devfile v2 is using an image which doesn't have /home/user folder

### ISSUE THREAD

**Issue by apupier** [abkieling/camel-demo#4]
the image https://github.com/abkieling/camel-demo/blob/a49df7d7db40d36e7f2c5c667924c0df6b1142e0/devfile.yaml#L24
doesn't have a /home/user folder which is tried to be used in here https://github.com/abkieling/camel-demo/blob/a49df7d7db40d36e7f2c5c667924c0df6b1142e0/devfile.yaml#L40 and here https://github.com/abkieling/camel-demo/blob/a49df7d7db40d36e7f2c5c667924c0df6b1142e0/devfile.yaml#L45

it results to this kind of errro when launching provided init-compile task:
```
[ERROR] Could not create local repository at /home/user/.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
```

either need to modify the image or the commands 
the image seems to be the same that is used when using devfile v1

the devfile V2 to v1 convertion is generating wrong commands too. The working_dir should not be $PROJECTS_ROOT anymore but $CHE_PROJECTS_ROOT/camel-demo but ti woudl break devfile v2 so cannot do the modification, see https://issues.redhat.com/browse/CRW-2492

**Comment by abkieling** [comment]
removed the wrong references to `.m2` folder
